version: '3'
services:
  app:
    build:
      context: ./backend
      args:
        - NODE_ENV=$NODE_ENV
        - VUE_APP_BASE_API=$VUE_APP_BASE_API
        - VUE_APP_VERSION=${VERSION}
        - VUE_APP_GOOGLE_API_KEY=$VUE_APP_GOOGLE_API_KEY
        - VUE_APP_SENTRY_DSN=$VUE_APP_SENTRY_DSN
        - VUE_APP_ERROR_ENVIRONMENT=$VUE_APP_ERROR_ENVIRONMENT
    image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-webadmin:${VERSION}
    networks:
      - internal
    ports: 
      - 8081:8080
    volumes:
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
    env_file:
      - .env

networks:
  internal:
    driver: bridge
