kind: ConfigMap
apiVersion: v1
metadata:
  name: sapawarga-webadmin-config-env
  namespace: sapawarga
data:
  VUE_APP_NODE_ENV: production
  VUE_APP_BASE_API: %VUE_APP_BASE_API%
  VUE_APP_VERSION: %VUE_APP_VERSION%
  VUE_SENTRY_DSN_API: %SENTRY_DSN_API%
  VUE_APP_ERROR_ENVIRONMENT: %APP_ERROR_ENVIRONMENT%
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: sapawarga
data:
  .dockerconfigjson: %dockerconfigjson% # Base64 decoded={"auths": {"your.registry.host": {"auth": "username:password"}}}
type: kubernetes.io/dockerconfigjson